### ISSUE TITLE
可以麻烦做一下优化吗？

### ISSUE THREAD

**Issue by giantss** [lazyee/flutter_custom_tab_bar#12]
1. #10 
2. #8 
3. #11 
4. 特别是#8 ，这个问题还会衍生出其他问题，比如 tab 1-50  ，当前选择1 ，然后点击 40，中间会滚动40个tab，会很卡顿。

**Comment by giantss** [comment]
以上问题我都在 [extended_tabs](https://github.com/fluttercandies/extended_tabs) 中得到解决了。

**Comment by lazyee** [comment]
好的，最近实在是太忙了，同时搞4个项目，实在是没空做修改，你能解决你的问题就好

**Comment by giantss** [comment]
。。。 这么卷吗？
