### ISSUE TITLE
Spacing problem

### ISSUE THREAD

**Issue by justkawal** [lazyee/flutter_custom_tab_bar#2]
Thanks for this great library

I found out a weird behaviour, When there are only 3 titles then the title doesn't spread to take the empty space by gapping away from each other.

**Comment by lazyee** [comment]
This function is not available at present, I will add it later, please wait for a moment

**Comment by lazyee** [comment]
This feature has been added, and you can set the width and physics properties to implement it
CustomTabBar(
            width: MediaQuery.of(context).size.width,
            physics: NeverScrollableScrollPhysics(),...)

**Comment by justkawal** [comment]
Thanks 💯
