### ISSUE TITLE
Indicator rendering issues (animation stops too early)

### ISSUE THREAD

**Issue by klondikedragon** [lazyee/flutter_custom_tab_bar#5]
This custom tab bar is lovely! Thank you for sharing this widget.

I'm using this on flutter web and the `LinearIndicator` is not always rendering correctly. 

In addition to changing a tab when tapped (clicked on the web), which works fine and the indicator is always rendered correctly, the app is programmatically switching the tab when the route changes by calling `animateToPage` (e.g., user changes address in web URL bar, or is following a deep link when the app first starts).

When the widget is first built, if the initial route causes some tab other than the first tab to be scrolled to via `animateToPage`, then the indicator is somehow drawn so that it spans all the way from the first tab to the selected tab. For example, if the initial route scrolls to the last tab, it looks like this (`/configure/archive` is route for last tab)

![image](https://user-images.githubusercontent.com/88254524/147313199-21708d02-bfee-4f53-b0dd-f4ca9c976931.png)

If the page that contains the custom tab bar is already loaded and the route changes, then it will render things more correctly, the tab indicator starts to "scroll" as you would expect as the content tied to the PageView also scrolls. But the linear indicator doesn't quite finish getting to the final position, even though the scrolled content is correctly positioned. For example, the page was loaded with the route on the first page, and then the web URL was changed in the browser address bar to change the route to indicate the last tab, and the indicator scrolled from the first tab to almost the last tab, but didn't quite make it:

![image](https://user-images.githubusercontent.com/88254524/147313397-ddf70b96-2ea9-41f4-9691-a974e5040e30.png)

It appears to be stopping the scroll on the indicator early.  For example, if the route is changed from the last tab to the second tab (so it's scrolling from right to left), then the indicator is too far to the right:

![image](https://user-images.githubusercontent.com/88254524/147313482-49072d7b-3d3c-454a-b2b4-576f9bcf43f0.png)

The indicator does always draw correctly if the user tapped/clicked the tab directly. So compare the above to what it looks like when it is clicked on directly:

![image](https://user-images.githubusercontent.com/88254524/147313653-d977dd8b-d225-41d5-a231-79c2c3865660.png)

If the page view scroll is manipulated by user input (e.g., arrow key on web), the indicator does track/render correctly all the way through the end of the scroll. So it appears that the indicator scroll is not tracking to the scroll position of the `PageController` if the page controller scroll position is manipulated programmatically (e.g., the `animateToPage`).

Here is the code at the top of the build function for the Widget that contains the CustomTabBar:

```dart
    // Sync page controller with current route
    // (only initiate change if route has changed since last time)
    _previousRoute ??= context.vRouter.url;
    if (_controller.hasClients && _previousRoute != context.vRouter.url) {
      _previousRoute = context.vRouter.url;
      _activelyScrolling = true;
      _logger.d(
          "route change initiate animation to tab ${widget.currentTabIndex}");
      _controller
          .animateToPage(widget.currentTabIndex,
              duration: animDuration, curve: Curves.easeIn)
          .then(
            (value) => setState(() => _activelyScrolling = false),
            onError: (err) => setState(() => _activelyScrolling = false),
          );
    }
```

And here is code excerpt later that builds the `CustomTabBar`:

```dart
            ...
            child: CustomTabBar(
              initialIndex: widget.currentTabIndex,
              itemCount: numTabs,
              height: 43,
              pageController: _controller,
              controlJump: false,
              onTapItem: (page) {
                var newRoute = AppRoutes.configureTabPages[
                    page.clamp(0, AppRoutes.configureTabPages.length - 1)];
                _logger.d("Tab onTap trigger route to $newRoute");
                context.vRouter.to(newRoute);
              },
              indicator: LinearIndicator(
                  color: theme.navigationPaneTheme.highlightColor ??
                      Colors.grey[700],
                  bottom: 0),
              builder: (context, index) {
                switch (index) {
                  case 0:
                    return getTabBarItem(index,
                        fui_icons.FluentIcons.organization_48_filled, 'Tab 1');
                  case 1:
                    return getTabBarItem(index, FluentIcons.data_flow, 'Tab 2');
                  case 2:
                    return getTabBarItem(index, FluentIcons.devices2, 'Tab 3');
                  case 3:
                    return getTabBarItem(index, FluentIcons.archive, 'Tab 4');
                  default:
                    return const Text('Unknown');
                }
              },
            ),
```

Note that `controlJump: false` so that the custom `onTapItem` callback will change the route, which then the widget gets built again and it triggers the `animateToPage` call the next time around. If any tab is tapped, it does correctly do the animation. It's only if the route changes for a reason other than `onTapItem` is called where the indicator rendering isn't right.

It's not specific to `LinearIndicator`, other indicators appear to have similar troubles (and the cause appears similar where it hasn't completely finished going through the animation of the indicator before it stops changing, etc.).

**Comment by lazyee** [comment]
This is a BUG, please use the 1.1.0 version of the package.


` flutter_custom_tab_bar: ^1.1.0`

Now You can use CustomTabBarController to control the jump of pageView
```dart
CustomTabBarController _tabBarController = CustomTabBarController();

CustomTabBar(
            tabBarController: _tabBarController,
            ...
            ),

_tabBarController.animateToIndex(_pageController, 1);
```

**Comment by klondikedragon** [comment]
@lazyee -- thank you, I can confirm using `1.1.2` this works now! I can use `_tabBarController.animateToIndex(...)` in conjunction with `_pageController.animateToPage(..., duration: kCustomerTabBarAnimDuration, curve: Curves.easeIn)` and the tab indicator scrolls perfectly now.

With 1.1.2 one issue remains where if the page is first built with the initialIndex set to the last tab (in the above example, index 3), then the indicator is still drawn underlining all four tabs (but with the last tab properly highlighted). This only occurs if the last tab is the initialIndex, if any other tab is the initialIndex then it draws correctly.

**Comment by lazyee** [comment]
@klondikedragon

**Comment by lazyee** [comment]
@klondikedragon 
Can you use 'flutter_custom_tab_bar: ^1.1.3' try again?
I remove 'initialIndex' of this version, because I think this parameter is not necessary now, now just use 'PageController(initialPage: 3)' to specify the initialPage
I have dealt with the problem you raised, and it did not appear again in my local environment. I hope you can try again and solve your problem

**Comment by klondikedragon** [comment]
@lazyee - version 1.1.3 works perfectly now! Thank you for the quick fixes!!
