### ISSUE TITLE
can you add "index" (int) and "indexIsChanging"(bool) ?

### ISSUE THREAD

**Issue by sahmirzali** [lazyee/flutter_custom_tab_bar#6]
First of All, thanks for the package, I really appreciate and liked your package. can you add these for CustomTabBarController ?

like in Tabbar Controller
CustomTabBarController _customTabBarController = CustomTabBarController();
like this - >  _customTabBarController.index; [int]
                    _customTabBarController.indexIsChanging; [bool]

**Comment by lazyee** [comment]
` _customTabBarController. CurrentIndex ` and ` _customTabBarController. IsChanging ` () has been added, please use the `flutter_custom_tab_bar: ^ 1.1.7` package
