### ISSUE TITLE
关于 onPageChanged 事件

### ISSUE THREAD

**Issue by giantss** [lazyee/flutter_custom_tab_bar#8]
滑动切换时是正常的触发下标，但如果是点击就会持续触发这个事件，直到点击的目标下标。

比如当前下标是1，如果我点击下标为5的tab，onPageChanged就会触发4次，下标是 2 3  4 5都会执行一遍。

**Comment by lazyee** [comment]
点击这个问题是因为PapeView直接调用animateToPage跳过去，所以会依次执行一遍。

**Comment by giantss** [comment]
> 

哦，请问一下有办法只触发一次吗？

**Comment by lazyee** [comment]
你看下这个库的实现(https://github.com/lazyee/flutter_tabs),或许可以解决你的问题

**Comment by giantss** [comment]
好的 谢谢
